version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: dockering/python/Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
    depends_on:
      - db
      - redis
  db:
    image: postgres:13-alpine
    user: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
    hostname: ${REDIS_HOSTNAME}
    volumes:
     - $PWD/redis-data:/var/lib/redisf
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  pg_data:
